# OTHER ANALYSIS

-- Overall Patient Count And Summary Stats
SELECT COUNT(*) AS total_patients, 
	AVG(TIMESTAMPDIFF(MINUTE, entry_time, completion_time)) AS avg_wait_time,
    MIN(TIMESTAMPDIFF(MINUTE, entry_time, completion_time)) AS min_wait_time,
    MAX(TIMESTAMPDIFF(MINUTE, entry_time, completion_time)) AS max_wait_time
FROM hospital_db.patients;

-- Total Number of Patients And Revenue Generated
SELECT COUNT(*) AS number_of_patients, 
    FORMAT(SUM(medication_revenue + consultation_revenue), 2) AS total_revenue
FROM hospital_db.patients;

-- Which Type of Doctor Saw the Most Patients?
SELECT DISTINCT doctor_type, 
	COUNT(patient_id) AS total_no_patients
FROM hospital_db.patients
GROUP BY doctor_type
ORDER BY total_no_patients;

-- Total Waiting Time by Patients per Doctor Type 
SELECT doctor_type, 
	ROUND(AVG(TIMESTAMPDIFF(SECOND, entry_time, post_consultation_time)) / 60, 3) AS avg_wait_time_minutes
FROM hospital_db.patients
GROUP BY doctor_type
ORDER BY avg_wait_time_minutes DESC;

-- Does the Financial Class of the Patient Affect Waiting Time?
SELECT financial_class, 
	SEC_TO_TIME(SUM(TIMESTAMPDIFF(SECOND, entry_time, post_consultation_time))) AS total_wait_time
FROM hospital_db.patients
GROUP BY financial_class
ORDER BY total_wait_time;

-- Average Wait Time And Total Revenue Generated by each Patient
SELECT patient_id,
	FORMAT(SUM(medication_revenue) + SUM(consultation_revenue), 2) AS total_revenue,
	ROUND(AVG(TIMESTAMPDIFF(MINUTE, entry_time, post_consultation_time)), 2) AS avg_wait_time_minutes
FROM hospital_db.patients
GROUP BY patient_id
ORDER BY total_revenue;